server:
  port: 9095

spring:
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: serkan.guner@yahoo.com
    password: hqik yqbk oeff xyhg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

authservice:
  secret:
    secret-key: ${JAVA14_SECRET_KEY}
    issuer: ${JAVA14_ISSUER}