spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: application-user

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

userservice:
  redis:
    host: localhost
    port: 6379

