spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: application-post
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
