server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/serkangnr/SocialMediaConfigServer.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "serkangnr"
          password: ${MEDIATOKEN}
          force-pull: true
          refreshRate: 1



