server:
  port: 9093

spring:
  data:
    mongodb:
      host: localhost
      port: 27027
      database: PostService
      username: bilge
      password: bilge!123

authservice:
  secret:
    secret-key: ${JAVA14_SECRET_KEY}
    issuer: ${JAVA14_ISSUER}