server:
  port: 80

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        #http://localhost/auth/findbyid/1
        #(?<segment>.*) -> /auth/findbyid/1 bu kismi yakalar.
        #/$\{segment} ->  geri kalan kismini ekler  http://localhost/api/v1/auth/findbyid/1 (/api/v1)
        # RewritePath: yeni yolumuzu tekrar yazmada yardimci olur.
        - RewritePath=/(?<segment>.*),/api/v1/$\{segment}
      routes:
        - id: auth-service
          uri: http://localhost:9090 #hedef adres
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: userprofile-service
          uri: http://localhost:9091 #hedef adres
          predicates:
            - Path=/userprofile/**
          filters:
            - name: CircuitBreaker
              args:
                name: userprofileCircuitBreaker
                fallbackUri: forward:/fallback/userprofile
  zipkin:
    base-url: http://localhost:9411/
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      enabled: true