server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/SocialMediaAuthDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

authservice:
  secret:
    secret-key: ${JAVA14_SECRET_KEY}
    issuer: ${JAVA14_ISSUER}



springdoc:
  swagger-ui:
    tryItOutEnabled: false

